[package]
name = "neuro_import"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "neuro_import"
crate-type = ["cdylib"]

[dependencies]
intan_importer = "0.1.0"
pyo3 = "0.23.3"
